title: "Lybra AI Lab"
logo: "/assets/images/logos/logo.png"  # или ваш путь к лого
favicon: "/assets/images/favicon.ico"
description: "Лаборатория экспериментов с нейросетями"
baseurl: "/lybra-ai-lab"
url: "https://lybra-bee.github.io"
github_username: "lybra-bee"

theme: jekyll-theme-primer
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  experiments:
    output: true
    permalink: /experiments/:path/

defaults:
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: "experiment"

navigation:
  - title: "🖥️ Лаборатория"
    url: /
  - title: "🔌 Оборудование"
    url: /hardware
  - title: "🏠 Основной сайт"
    url: https://lybra-bee.github.io/
