title: "Lybra AI Lab"
description: "Практические эксперименты с нейросетями на бюджетном железе"
baseurl: "/lybra-ai-lab"
url: "https://lybra-bee.github.io"

# Настройки сборки
markdown: kramdown
permalink: pretty

# Коллекции
collections:
  experiments:
    output: true
    permalink: /experiments/:path/

# Данные - ИСПРАВЛЕННЫЙ РАЗДЕЛ
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: "experiment"

# ДОБАВИТЬ ЭТИ НАСТРОЙКИ
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Настройка для GitHub Pages
repository: lybra-bee/lybra-ai-lab
